"""Offline, paper-only strategy simulation."""

from xgedge.simulation.paper import (
    DEFAULT_SCORE_POLICY,
    PAPER_ONLY,
    STARTING_BALANCE_RUB,
    TARGET_BALANCE_RUB,
    BetPlaced,
    BetSettled,
    ConservativeEdgeStrategy,
    CycleSnapshot,
    CycleStarted,
    EventKind,
    FlatOnePercentStrategy,
    FractionalKellyStrategy,
    PaperEvent,
    PaperMetrics,
    PaperSimulator,
    PreregisteredScorePolicy,
    RuinObserved,
    SettlementResult,
    StakeDecision,
    StrategyRanking,
    TargetObserved,
    preregistered_score,
    rank_strategies,
)

__all__ = [
    "DEFAULT_SCORE_POLICY",
    "PAPER_ONLY",
    "STARTING_BALANCE_RUB",
    "TARGET_BALANCE_RUB",
    "BetPlaced",
    "BetSettled",
    "ConservativeEdgeStrategy",
    "CycleSnapshot",
    "CycleStarted",
    "EventKind",
    "FlatOnePercentStrategy",
    "FractionalKellyStrategy",
    "PaperEvent",
    "PaperMetrics",
    "PaperSimulator",
    "PreregisteredScorePolicy",
    "RuinObserved",
    "SettlementResult",
    "StakeDecision",
    "StrategyRanking",
    "TargetObserved",
    "preregistered_score",
    "rank_strategies",
]
